/**
 * reportGenerator.js
 * 
 * Generates a professional, multi-page PDF analytics report using jsPDF.
 * Charts are captured as images via html2canvas.
 * 
 * Main entry point: generateAnalyticsReport(analyticsData, userData, onProgress)
 */

import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import {
  formatPercentage,
  formatScore,
  formatTime,
  formatDate,
  formatDateTime,
  getPerformanceBadge,
  generateInsights,
  createRecommendations,
} from './reportFormatters';

// ─── CONSTANTS ──────────────────────────────────────────────

const PAGE_WIDTH = 210; // A4 mm
const PAGE_HEIGHT = 297;
const MARGIN = 20;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const FOOTER_Y = PAGE_HEIGHT - 12;

const COLORS = {
  primary: [20, 184, 166],      // teal-500
  primaryDark: [13, 148, 136],  // teal-600
  accent: [45, 212, 191],       // teal-300
  bg: [15, 15, 15],             // near-black
  bgCard: [30, 30, 30],         // card bg
  bgCardLight: [40, 40, 40],
  text: [255, 255, 255],
  textSecondary: [161, 161, 170],
  success: [16, 185, 129],
  warning: [245, 158, 11],
  danger: [239, 68, 68],
  physics: [59, 130, 246],
  chemistry: [16, 185, 129],
  maths: [249, 115, 22],
};

// ─── HELPERS ────────────────────────────────────────────────

/** Set fill + text color from an RGB array. */
const setColor = (doc, rgb) => {
  doc.setTextColor(rgb[0], rgb[1], rgb[2]);
};

const setFill = (doc, rgb) => {
  doc.setFillColor(rgb[0], rgb[1], rgb[2]);
};

const setDraw = (doc, rgb) => {
  doc.setDrawColor(rgb[0], rgb[1], rgb[2]);
};

/** Draw a rounded rectangle. */
const roundedRect = (doc, x, y, w, h, r, style = 'F') => {
  doc.roundedRect(x, y, w, h, r, r, style);
};

/** Draw page background. */
const drawPageBg = (doc) => {
  setFill(doc, COLORS.bg);
  doc.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, 'F');
};

/** Add header bar (used on all pages except cover). */
const addHeader = (doc, title) => {
  // Header bar
  setFill(doc, COLORS.primaryDark);
  doc.rect(0, 0, PAGE_WIDTH, 18, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  setColor(doc, COLORS.text);
  doc.text('KakshaAI', MARGIN, 12);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(title, PAGE_WIDTH - MARGIN, 12, { align: 'right' });
};

/** Add footer with page number. */
const addFooter = (doc, pageNum, totalPages) => {
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  setColor(doc, COLORS.textSecondary);
  doc.text(
    `Page ${pageNum} of ${totalPages}`,
    PAGE_WIDTH / 2,
    FOOTER_Y,
    { align: 'center' }
  );
  doc.text('Generated by KakshaAI', MARGIN, FOOTER_Y);
  doc.text(formatDateTime(new Date()), PAGE_WIDTH - MARGIN, FOOTER_Y, { align: 'right' });
};

/** Start a new page with background, header, and return starting Y. */
const newPage = (doc, title) => {
  doc.addPage();
  drawPageBg(doc);
  addHeader(doc, title);
  return 26; // Y position after header
};

/** Draw a section title and return Y after it. */
const sectionTitle = (doc, title, y) => {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  setColor(doc, COLORS.primary);
  doc.text(title, MARGIN, y);

  // Underline
  setDraw(doc, COLORS.primary);
  doc.setLineWidth(0.5);
  doc.line(MARGIN, y + 2, MARGIN + doc.getTextWidth(title), y + 2);

  return y + 10;
};

/** Draw a KPI card. */
const drawKPICard = (doc, x, y, w, h, label, value, sublabel) => {
  setFill(doc, COLORS.bgCard);
  roundedRect(doc, x, y, w, h, 3);

  // Value
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  setColor(doc, COLORS.accent);
  doc.text(String(value), x + w / 2, y + h / 2 - 2, { align: 'center' });

  // Label
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  setColor(doc, COLORS.textSecondary);
  doc.text(label, x + w / 2, y + h / 2 + 8, { align: 'center' });

  // Sublabel
  if (sublabel) {
    doc.setFontSize(7);
    doc.text(sublabel, x + w / 2, y + h / 2 + 14, { align: 'center' });
  }
};

/** Draw a horizontal bar chart row. */
const drawBar = (doc, x, y, maxW, pct, color, label, valueText) => {
  const barH = 8;

  // Label
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  setColor(doc, COLORS.text);
  doc.text(label, x, y + barH / 2 + 1);

  const barX = x + 45;
  const barW = maxW - 65;

  // Track
  setFill(doc, COLORS.bgCardLight);
  roundedRect(doc, barX, y, barW, barH, 2);

  // Fill
  const fillW = Math.max(2, (pct / 100) * barW);
  setFill(doc, color);
  roundedRect(doc, barX, y, fillW, barH, 2);

  // Value
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  setColor(doc, color);
  doc.text(valueText, barX + barW + 5, y + barH / 2 + 1);
};

/** Draw a simple table. */
const drawTable = (doc, x, y, headers, rows, colWidths) => {
  const rowH = 8;

  // Header
  setFill(doc, COLORS.bgCard);
  doc.rect(x, y, CONTENT_WIDTH, rowH, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  setColor(doc, COLORS.accent);

  let cx = x + 3;
  headers.forEach((h, i) => {
    doc.text(h, cx, y + rowH / 2 + 1);
    cx += colWidths[i];
  });

  y += rowH;

  // Rows
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  rows.forEach((row, ri) => {
    if (ri % 2 === 0) {
      setFill(doc, COLORS.bgCardLight);
      doc.rect(x, y, CONTENT_WIDTH, rowH, 'F');
    }

    setColor(doc, COLORS.text);
    cx = x + 3;
    row.forEach((cell, ci) => {
      doc.text(String(cell), cx, y + rowH / 2 + 1);
      cx += colWidths[ci];
    });

    y += rowH;
  });

  return y + 4;
};

// ─── CHART CAPTURE ──────────────────────────────────────────

/**
 * Capture a DOM element as a JPEG data URL using html2canvas.
 * @param {string} elementId - The id of the element to capture.
 * @returns {Promise<string|null>} JPEG data URL or null on failure.
 */
export async function captureChartAsImage(elementId) {
  try {
    const el = document.getElementById(elementId);
    if (!el) {
      console.warn(`Chart element #${elementId} not found, skipping.`);
      return null;
    }

    const canvas = await html2canvas(el, {
      backgroundColor: '#0f0f0f',
      scale: 1.5,       // balance quality vs. size
      useCORS: true,
      logging: false,
    });

    return canvas.toDataURL('image/jpeg', 0.82);
  } catch (err) {
    console.error(`Failed to capture chart #${elementId}:`, err);
    return null;
  }
}

// ─── PAGE BUILDERS ──────────────────────────────────────────

/** Page 1: Cover Page */
function addCoverPage(doc, userData) {
  drawPageBg(doc);

  // Decorative gradient band
  setFill(doc, COLORS.primaryDark);
  doc.rect(0, 0, PAGE_WIDTH, 90, 'F');

  // Top accent line
  setFill(doc, COLORS.accent);
  doc.rect(0, 0, PAGE_WIDTH, 3, 'F');

  // Branding
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(28);
  setColor(doc, COLORS.text);
  doc.text('KakshaAI', PAGE_WIDTH / 2, 40, { align: 'center' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(12);
  setColor(doc, COLORS.accent);
  doc.text('Smart Learning. Smarter Results.', PAGE_WIDTH / 2, 52, { align: 'center' });

  // Report title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(32);
  setColor(doc, COLORS.text);
  doc.text('Performance', PAGE_WIDTH / 2, 130, { align: 'center' });
  doc.text('Analytics Report', PAGE_WIDTH / 2, 145, { align: 'center' });

  // Decorative line
  setFill(doc, COLORS.primary);
  doc.rect(PAGE_WIDTH / 2 - 25, 155, 50, 1.5, 'F');

  // Student info
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(14);
  setColor(doc, COLORS.textSecondary);
  doc.text('Prepared for', PAGE_WIDTH / 2, 175, { align: 'center' });

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  setColor(doc, COLORS.text);
  const studentName = userData?.user_metadata?.full_name || userData?.name || userData?.email || 'Student';
  doc.text(studentName, PAGE_WIDTH / 2, 190, { align: 'center' });

  if (userData?.email) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    setColor(doc, COLORS.textSecondary);
    doc.text(userData.email, PAGE_WIDTH / 2, 200, { align: 'center' });
  }

  // Date & period
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  setColor(doc, COLORS.textSecondary);
  doc.text(`Generated on ${formatDateTime(new Date())}`, PAGE_WIDTH / 2, 230, { align: 'center' });
  doc.text('Report Period: Last 30 Days', PAGE_WIDTH / 2, 240, { align: 'center' });

  // Bottom accent
  setFill(doc, COLORS.primary);
  doc.rect(0, PAGE_HEIGHT - 6, PAGE_WIDTH, 6, 'F');
}

/** Page 2: Summary Dashboard */
function addSummaryPage(doc, kpi, subjectPerformance) {
  let y = newPage(doc, 'Summary Dashboard');

  y = sectionTitle(doc, 'Key Performance Indicators', y);

  const cardW = (CONTENT_WIDTH - 9) / 4;
  const cardH = 34;

  drawKPICard(doc, MARGIN, y, cardW, cardH,
    'Tests Completed', kpi?.totalTests ?? 0, 'Total mock tests');

  drawKPICard(doc, MARGIN + cardW + 3, y, cardW, cardH,
    'Percentile Rank', formatPercentage(kpi?.percentileRank), 'Among all users');

  const impSign = (kpi?.overallImprovement ?? 0) >= 0 ? '+' : '';
  drawKPICard(doc, MARGIN + (cardW + 3) * 2, y, cardW, cardH,
    'Improvement', `${impSign}${formatPercentage(kpi?.overallImprovement)}`, 'Score trend');

  const bestTopic = kpi?.bestScoringTopic;
  drawKPICard(doc, MARGIN + (cardW + 3) * 3, y, cardW, cardH,
    'Best Topic', bestTopic?.name ?? 'N/A',
    bestTopic ? `${formatPercentage(bestTopic.accuracy)} accuracy` : '');

  y += cardH + 12;

  // Overall badge
  const avgPct = subjectPerformance?.length
    ? subjectPerformance.reduce((s, sp) => s + (sp.percentage || 0), 0) / subjectPerformance.length
    : 0;
  const badge = getPerformanceBadge(avgPct);

  y = sectionTitle(doc, 'Overall Assessment', y);
  setFill(doc, COLORS.bgCard);
  roundedRect(doc, MARGIN, y, CONTENT_WIDTH, 24, 3);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  setColor(doc, avgPct >= 70 ? COLORS.success : avgPct >= 50 ? COLORS.warning : COLORS.danger);
  doc.text(badge, MARGIN + 10, y + 10);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  setColor(doc, COLORS.textSecondary);
  doc.text(
    `Overall average: ${formatPercentage(avgPct)} across ${subjectPerformance?.length ?? 0} subjects.`,
    MARGIN + 10, y + 18
  );

  y += 32;

  // Quick insights
  y = sectionTitle(doc, 'Quick Insights', y);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  setColor(doc, COLORS.text);

  const insights = generateInsights({ kpi, subjectPerformance });
  insights.forEach((ins) => {
    if (y > PAGE_HEIGHT - 30) return;
    doc.text(`•  ${ins}`, MARGIN + 4, y);
    y += 7;
  });

  return y;
}

/** Page 3: Subject Performance */
function addSubjectPerformancePage(doc, subjectPerformance, chartImage) {
  let y = newPage(doc, 'Subject Performance');
  y = sectionTitle(doc, 'Subject-wise Breakdown', y);

  // Chart image
  if (chartImage) {
    try {
      doc.addImage(chartImage, 'JPEG', MARGIN, y, CONTENT_WIDTH, 80);
      y += 85;
    } catch (e) {
      console.error('Failed to add subject chart image:', e);
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(10);
      setColor(doc, COLORS.textSecondary);
      doc.text('Chart could not be rendered.', MARGIN, y + 10);
      y += 20;
    }
  }

  // Bar chart fallback / detail
  if (subjectPerformance?.length) {
    y = sectionTitle(doc, 'Detailed Statistics', y);

    subjectPerformance.forEach((sp) => {
      if (y > PAGE_HEIGHT - 40) return;
      const color = sp.color
        ? sp.color.startsWith('#')
          ? hexToRgb(sp.color)
          : COLORS.text
        : COLORS.primary;

      drawBar(doc, MARGIN, y, CONTENT_WIDTH, sp.percentage ?? 0, color,
        sp.subject ?? 'Unknown',
        `${formatPercentage(sp.percentage)}  (${formatScore(sp.correctAnswers, sp.totalQuestions)})`
      );
      y += 14;
    });

    // Table
    y += 4;
    const headers = ['Subject', 'Accuracy', 'Correct', 'Total', 'Badge'];
    const colWidths = [40, 30, 30, 30, 40];
    const rows = subjectPerformance.map((sp) => [
      sp.subject ?? '',
      formatPercentage(sp.percentage),
      String(sp.correctAnswers ?? 0),
      String(sp.totalQuestions ?? 0),
      getPerformanceBadge(sp.percentage),
    ]);
    y = drawTable(doc, MARGIN, y, headers, rows, colWidths);
  }

  return y;
}

/** Page 4: Score Trends */
function addScoreTrendsPage(doc, scoreTrends, chartImage) {
  let y = newPage(doc, 'Score Trends');
  y = sectionTitle(doc, 'Score Progression Over Time', y);

  if (chartImage) {
    try {
      doc.addImage(chartImage, 'JPEG', MARGIN, y, CONTENT_WIDTH, 90);
      y += 95;
    } catch (e) {
      console.error('Failed to add score trends chart:', e);
      y += 10;
    }
  }

  // Highlights
  if (scoreTrends?.length >= 2) {
    y = sectionTitle(doc, 'Trend Highlights', y);

    const subjects = ['physics', 'chemistry', 'mathematics'];
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);

    subjects.forEach((subj) => {
      if (y > PAGE_HEIGHT - 25) return;
      const vals = scoreTrends
        .map((s) => s[subj])
        .filter((v) => v != null);
      if (vals.length < 2) return;

      const first = vals[0];
      const last = vals[vals.length - 1];
      const diff = last - first;
      const arrow = diff >= 0 ? '↑' : '↓';
      const clr = diff >= 0 ? COLORS.success : COLORS.danger;

      setColor(doc, clr);
      const name = subj.charAt(0).toUpperCase() + subj.slice(1);
      doc.text(
        `${arrow} ${name}: ${first}% → ${last}% (${diff >= 0 ? '+' : ''}${diff.toFixed(1)}%)`,
        MARGIN + 4, y
      );
      y += 7;
    });
  } else {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(10);
    setColor(doc, COLORS.textSecondary);
    doc.text('Not enough data to show trends. Take more tests!', MARGIN + 4, y);
    y += 10;
  }

  return y;
}

/** Page 5: Weekly Activity */
function addWeeklyActivityPage(doc, weeklyActivity, chartImage) {
  let y = newPage(doc, 'Weekly Activity');
  y = sectionTitle(doc, 'Weekly Study Activity', y);

  if (chartImage) {
    try {
      doc.addImage(chartImage, 'JPEG', MARGIN, y, CONTENT_WIDTH, 85);
      y += 90;
    } catch (e) {
      console.error('Failed to add weekly activity chart:', e);
    }
  }

  if (weeklyActivity?.length) {
    y = sectionTitle(doc, 'Daily Breakdown', y);

    const headers = ['Day', 'Questions', 'Accuracy', 'Study Time'];
    const colWidths = [40, 40, 40, 50];
    const rows = weeklyActivity.map((d) => [
      d.dayName || formatDate(d.date),
      String(d.questionsAttempted ?? 0),
      formatPercentage(d.accuracy),
      formatTime(d.studyTime),
    ]);
    y = drawTable(doc, MARGIN, y, headers, rows, colWidths);

    // Consistency
    const daysActive = weeklyActivity.filter((d) => (d.questionsAttempted || 0) > 0).length;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    setColor(doc, COLORS.textSecondary);
    doc.text(`Active days this week: ${daysActive} / ${weeklyActivity.length}`, MARGIN + 4, y);
  }
}

/** Page 6: Topic Analysis */
function addTopicAnalysisPage(doc, topicAnalysis) {
  let y = newPage(doc, 'Topic Analysis');
  y = sectionTitle(doc, 'Strongest Topics', y);

  const strongest = topicAnalysis?.strongest || [];
  const weakest = topicAnalysis?.weakest || [];

  if (strongest.length) {
    strongest.slice(0, 5).forEach((t, i) => {
      if (y > PAGE_HEIGHT - 25) return;
      setFill(doc, COLORS.bgCard);
      roundedRect(doc, MARGIN, y, CONTENT_WIDTH, 12, 2);

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      setColor(doc, COLORS.success);
      doc.text(`${i + 1}. ${t.topic}`, MARGIN + 4, y + 8);

      doc.setFont('helvetica', 'normal');
      setColor(doc, COLORS.text);
      doc.text(
        `Accuracy: ${formatPercentage(t.accuracy)}  |  ${formatScore(t.correct, t.total)}  |  ${t.testCount ?? 0} tests`,
        MARGIN + 60, y + 8
      );
      y += 16;
    });
  } else {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(10);
    setColor(doc, COLORS.textSecondary);
    doc.text('No strong topic data available yet.', MARGIN + 4, y);
    y += 12;
  }

  y += 6;
  y = sectionTitle(doc, 'Weakest Topics', y);

  if (weakest.length) {
    weakest.slice(0, 5).forEach((t, i) => {
      if (y > PAGE_HEIGHT - 25) return;
      setFill(doc, COLORS.bgCard);
      roundedRect(doc, MARGIN, y, CONTENT_WIDTH, 12, 2);

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      setColor(doc, COLORS.danger);
      doc.text(`${i + 1}. ${t.topic}`, MARGIN + 4, y + 8);

      doc.setFont('helvetica', 'normal');
      setColor(doc, COLORS.text);
      doc.text(
        `Accuracy: ${formatPercentage(t.accuracy)}  |  ${formatScore(t.correct, t.total)}  |  ${t.testCount ?? 0} tests`,
        MARGIN + 60, y + 8
      );
      y += 16;
    });
  } else {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(10);
    setColor(doc, COLORS.textSecondary);
    doc.text('No weak topic data available yet.', MARGIN + 4, y);
    y += 12;
  }

  // Recommendations
  y += 6;
  y = sectionTitle(doc, 'Recommendations', y);
  const recs = createRecommendations(weakest);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  setColor(doc, COLORS.text);
  recs.forEach((r) => {
    if (y > PAGE_HEIGHT - 20) return;
    const lines = doc.splitTextToSize(`•  ${r}`, CONTENT_WIDTH - 8);
    doc.text(lines, MARGIN + 4, y);
    y += lines.length * 5 + 3;
  });
}

/** Page 7: MHT-CET Prediction */
function addPredictionPage(doc, prediction) {
  let y = newPage(doc, 'MHT-CET Prediction');
  y = sectionTitle(doc, 'MHT-CET Score Prediction', y);

  const preds = prediction?.predictions;

  if (preds) {
    const scenarios = [
      { key: 'easy', label: 'Easy Shift', color: COLORS.success },
      { key: 'moderate', label: 'Moderate Shift', color: COLORS.warning },
      { key: 'hard', label: 'Hard Shift', color: COLORS.danger },
    ];

    const cardW = (CONTENT_WIDTH - 6) / 3;
    const cardH = 44;

    scenarios.forEach((sc, i) => {
      const data = preds[sc.key];
      if (!data) return;
      const x = MARGIN + i * (cardW + 3);

      setFill(doc, COLORS.bgCard);
      roundedRect(doc, x, y, cardW, cardH, 3);

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      setColor(doc, sc.color);
      doc.text(sc.label, x + cardW / 2, y + 10, { align: 'center' });

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(22);
      setColor(doc, COLORS.text);
      doc.text(String(data.score ?? '--'), x + cardW / 2, y + 26, { align: 'center' });

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      setColor(doc, COLORS.textSecondary);
      doc.text(`${formatPercentage(data.percentile)} percentile`, x + cardW / 2, y + 35, { align: 'center' });
    });

    y += cardH + 12;
  }

  // Confidence & data points
  if (prediction?.confidenceLevel) {
    y = sectionTitle(doc, 'Prediction Details', y);

    setFill(doc, COLORS.bgCard);
    roundedRect(doc, MARGIN, y, CONTENT_WIDTH, 36, 3);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    const confColor = prediction.confidenceLevel === 'High' ? COLORS.success
      : prediction.confidenceLevel === 'Medium' ? COLORS.warning : COLORS.danger;
    setColor(doc, confColor);
    doc.text(`Confidence: ${prediction.confidenceLevel}`, MARGIN + 8, y + 10);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    setColor(doc, COLORS.text);

    const dp = prediction.dataPoints;
    if (dp) {
      doc.text(`Mock tests completed: ${dp.mockTestsCompleted ?? 'N/A'}`, MARGIN + 8, y + 20);
      doc.text(`Total study hours: ${dp.totalStudyHours ?? 'N/A'}`, MARGIN + 80, y + 20);
      doc.text(`Questions attempted: ${dp.questionsAttempted ?? 'N/A'}`, MARGIN + 8, y + 28);
    }

    y += 44;
  }

  // Disclaimer
  if (prediction?.disclaimer) {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(8);
    setColor(doc, COLORS.textSecondary);
    const lines = doc.splitTextToSize(prediction.disclaimer, CONTENT_WIDTH - 8);
    doc.text(lines, MARGIN + 4, y);
    y += lines.length * 4 + 4;
  }

  // Suggestions
  y += 4;
  y = sectionTitle(doc, 'Personalized Suggestions', y);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  setColor(doc, COLORS.text);

  const suggestions = [
    'Focus on your weakest subject to maximize overall score gains.',
    'Practice under timed conditions to improve speed and accuracy.',
    'Review error patterns to eliminate recurring mistakes.',
    'Take at least 2-3 full mock tests per week for consistent improvement.',
  ];
  suggestions.forEach((s) => {
    if (y > PAGE_HEIGHT - 20) return;
    doc.text(`•  ${s}`, MARGIN + 4, y);
    y += 7;
  });
}

/** Page 8: Time Distribution / Management */
function addTimeManagementPage(doc, timeDistribution, timeManagement, chartImage) {
  let y = newPage(doc, 'Time Management');
  y = sectionTitle(doc, 'Time Distribution', y);

  if (chartImage) {
    try {
      doc.addImage(chartImage, 'JPEG', MARGIN, y, CONTENT_WIDTH, 80);
      y += 85;
    } catch (e) {
      console.error('Failed to add time chart:', e);
    }
  }

  // Table
  if (timeDistribution?.length) {
    const headers = ['Subject', 'Time Spent', 'Percentage'];
    const colWidths = [60, 55, 55];
    const rows = timeDistribution.map((t) => [
      t.subject ?? '',
      formatTime(t.seconds),
      formatPercentage(t.percentage),
    ]);
    y = drawTable(doc, MARGIN, y, headers, rows, colWidths);
  }

  // Time per question
  if (timeManagement) {
    y += 4;
    y = sectionTitle(doc, 'Efficiency Metrics', y);

    setFill(doc, COLORS.bgCard);
    roundedRect(doc, MARGIN, y, CONTENT_WIDTH, 32, 3);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    setColor(doc, COLORS.text);
    doc.text(`Avg. time per question: ${timeManagement.overall ?? 'N/A'}s`, MARGIN + 8, y + 10);
    doc.text(`Physics: ${timeManagement.physics ?? 'N/A'}s`, MARGIN + 8, y + 20);
    doc.text(`Chemistry: ${timeManagement.chemistry ?? 'N/A'}s`, MARGIN + 80, y + 20);
    doc.text(`Mathematics: ${timeManagement.mathematics ?? 'N/A'}s`, MARGIN + 8, y + 28);

    y += 38;
  }
}

/** Page 9: Error Patterns */
function addErrorPatternsPage(doc, errorPatterns) {
  let y = newPage(doc, 'Error Patterns');
  y = sectionTitle(doc, 'Error Pattern Analysis', y);

  const cats = errorPatterns?.categories;
  if (cats?.length) {
    cats.forEach((cat) => {
      if (y > PAGE_HEIGHT - 30) return;

      setFill(doc, COLORS.bgCard);
      roundedRect(doc, MARGIN, y, CONTENT_WIDTH, 18, 2);

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      setColor(doc, COLORS.danger);
      doc.text(cat.name ?? 'Unknown', MARGIN + 6, y + 8);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      setColor(doc, COLORS.text);
      doc.text(
        `Error rate: ${formatPercentage(cat.errorRate)} — ${cat.incorrectCount ?? 0} incorrect out of ${cat.totalAttempts ?? 0} attempts`,
        MARGIN + 6, y + 15
      );
      y += 22;
    });
  } else {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(10);
    setColor(doc, COLORS.textSecondary);
    doc.text('No error pattern data available yet.', MARGIN + 4, y);
    y += 12;
  }

  // Recommendations
  y += 8;
  y = sectionTitle(doc, 'Improvement Recommendations', y);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  setColor(doc, COLORS.text);

  const tips = [
    'Review incorrect answers immediately after each test to learn from mistakes.',
    'Focus on conceptual understanding rather than rote memorization.',
    'Practice similar question types to address high-error categories.',
    'Use spaced repetition: revisit weak areas every 2-3 days.',
    'Time yourself on difficult questions to improve decision-making under pressure.',
  ];
  tips.forEach((t) => {
    if (y > PAGE_HEIGHT - 20) return;
    doc.text(`•  ${t}`, MARGIN + 4, y);
    y += 7;
  });
}

/** Page 10: Goals & Progress */
function addGoalsPage(doc, goals) {
  let y = newPage(doc, 'Goals & Progress');
  y = sectionTitle(doc, 'Study Goals Progress', y);

  if (goals) {
    const goalItems = [
      {
        label: 'Daily Goal',
        progress: goals.dailyProgress ?? 0,
        target: goals.dailyGoal ?? 50,
      },
      {
        label: 'Weekly Goal',
        progress: goals.weeklyProgress ?? 0,
        target: goals.weeklyGoal ?? 350,
      },
    ];

    goalItems.forEach((g) => {
      const pct = g.target > 0 ? Math.min(100, (g.progress / g.target) * 100) : 0;

      setFill(doc, COLORS.bgCard);
      roundedRect(doc, MARGIN, y, CONTENT_WIDTH, 28, 3);

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      setColor(doc, COLORS.text);
      doc.text(g.label, MARGIN + 6, y + 10);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      setColor(doc, COLORS.textSecondary);
      doc.text(`${g.progress} / ${g.target} questions`, MARGIN + 6, y + 20);

      // Progress bar
      const barX = MARGIN + 90;
      const barW = CONTENT_WIDTH - 120;
      setFill(doc, COLORS.bgCardLight);
      roundedRect(doc, barX, y + 8, barW, 10, 3);

      const fillColor = pct >= 100 ? COLORS.success : pct >= 50 ? COLORS.warning : COLORS.danger;
      setFill(doc, fillColor);
      roundedRect(doc, barX, y + 8, Math.max(2, (pct / 100) * barW), 10, 3);

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      setColor(doc, fillColor);
      doc.text(`${Math.round(pct)}%`, barX + barW + 4, y + 16);

      y += 34;
    });
  } else {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(10);
    setColor(doc, COLORS.textSecondary);
    doc.text('No goal data available.', MARGIN + 4, y);
    y += 12;
  }

  // Motivational
  y += 10;
  y = sectionTitle(doc, 'Keep Going!', y);
  setFill(doc, COLORS.bgCard);
  roundedRect(doc, MARGIN, y, CONTENT_WIDTH, 40, 3);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  setColor(doc, COLORS.text);

  const motivational = [
    '"Success is the sum of small efforts, repeated day in and day out."',
    '',
    'Stay consistent with your daily goals and you will see steady improvement.',
    'Every question you practice brings you closer to your target score.',
  ];
  motivational.forEach((line, i) => {
    doc.text(line, MARGIN + 8, y + 10 + i * 7);
  });

  y += 50;
}

/** Page 11: Final Summary */
function addFinalSummaryPage(doc, analyticsData) {
  let y = newPage(doc, 'Final Summary');
  y = sectionTitle(doc, 'Overall Assessment', y);

  const kpi = analyticsData?.kpi;
  const subjectPerformance = analyticsData?.subjectPerformance;

  const avgPct = subjectPerformance?.length
    ? subjectPerformance.reduce((s, sp) => s + (sp.percentage || 0), 0) / subjectPerformance.length
    : 0;
  const badge = getPerformanceBadge(avgPct);

  setFill(doc, COLORS.bgCard);
  roundedRect(doc, MARGIN, y, CONTENT_WIDTH, 28, 3);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  setColor(doc, avgPct >= 70 ? COLORS.success : avgPct >= 50 ? COLORS.warning : COLORS.danger);
  doc.text(`Performance Level: ${badge}`, MARGIN + 8, y + 12);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  setColor(doc, COLORS.textSecondary);
  doc.text(
    `Based on ${kpi?.totalTests ?? 0} tests with an average accuracy of ${formatPercentage(avgPct)}.`,
    MARGIN + 8, y + 22
  );

  y += 36;

  // Next steps
  y = sectionTitle(doc, 'Suggested Next Steps', y);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  setColor(doc, COLORS.text);

  const steps = [
    '1.  Focus on your weakest subject to bring up overall performance.',
    '2.  Attempt at least 2 full-length mock tests per week.',
    '3.  Review mistake patterns and track improvements weekly.',
    '4.  Allocate study time proportionally to difficulty areas.',
    '5.  Use KakshaAI daily to build consistency and track progress.',
  ];
  steps.forEach((step) => {
    if (y > PAGE_HEIGHT - 20) return;
    doc.text(step, MARGIN + 4, y);
    y += 8;
  });

  y += 10;

  // Study plan suggestion
  y = sectionTitle(doc, 'Recommended Study Plan', y);

  setFill(doc, COLORS.bgCard);
  roundedRect(doc, MARGIN, y, CONTENT_WIDTH, 60, 3);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  setColor(doc, COLORS.text);

  const plan = [
    'Mon — Physics concepts + practice (1.5 hrs)',
    'Tue — Chemistry theory + MCQs (1.5 hrs)',
    'Wed — Mathematics problem solving (1.5 hrs)',
    'Thu — Mixed subject practice test (2 hrs)',
    'Fri — Weak topic revision (1.5 hrs)',
    'Sat — Full mock test + analysis (3 hrs)',
    'Sun — Light revision + error review (1 hr)',
  ];
  plan.forEach((p, i) => {
    doc.text(p, MARGIN + 8, y + 8 + i * 7);
  });

  y += 68;

  // Closing
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(10);
  setColor(doc, COLORS.textSecondary);
  doc.text('This report is auto-generated by KakshaAI based on your learning data.', MARGIN + 4, y);
  y += 6;
  doc.text('For the latest analytics, visit the Performance Analytics page on KakshaAI.', MARGIN + 4, y);

  // Bottom accent
  setFill(doc, COLORS.primary);
  doc.rect(0, PAGE_HEIGHT - 6, PAGE_WIDTH, 6, 'F');
}

// ─── HEX TO RGB HELPER ─────────────────────────────────────

function hexToRgb(hex) {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result
    ? [parseInt(result[1], 16), parseInt(result[2], 16), parseInt(result[3], 16)]
    : COLORS.text;
}

// ─── MAIN ENTRY POINT ──────────────────────────────────────

/**
 * Generate a comprehensive PDF analytics report.
 *
 * @param {object} analyticsData - The full analytics data object from Analytics.jsx state.
 * @param {object} userData      - Current user object (email, name / user_metadata).
 * @param {function} onProgress  - Optional callback (progressPercent: number) => void.
 * @returns {Promise<void>} Triggers browser download of the PDF.
 */
export async function generateAnalyticsReport(analyticsData, userData, onProgress) {
  const progress = (pct) => {
    if (typeof onProgress === 'function') onProgress(pct);
  };

  if (!analyticsData) {
    throw new Error('No analytics data provided.');
  }

  // ── Create document ───────────────────────────────────────
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
    compress: true,
  });

  progress(5);

  // ── Page 1: Cover ─────────────────────────────────────────
  addCoverPage(doc, userData);
  progress(10);

  // ── Page 2: Summary ───────────────────────────────────────
  addSummaryPage(doc, analyticsData.kpi, analyticsData.subjectPerformance);
  progress(18);

  // ── Capture charts ────────────────────────────────────────
  progress(20);

  const chartIds = [
    'report-subject-performance-chart',
    'report-score-trends-chart',
    'report-weekly-activity-chart',
    'report-time-distribution-chart',
  ];

  const chartImages = {};
  for (let i = 0; i < chartIds.length; i++) {
    chartImages[chartIds[i]] = await captureChartAsImage(chartIds[i]);
    progress(20 + Math.round(((i + 1) / chartIds.length) * 25));
  }

  progress(48);

  // ── Page 3: Subject Performance ───────────────────────────
  addSubjectPerformancePage(
    doc,
    analyticsData.subjectPerformance,
    chartImages['report-subject-performance-chart']
  );
  progress(55);

  // ── Page 4: Score Trends ──────────────────────────────────
  addScoreTrendsPage(
    doc,
    analyticsData.scoreTrends,
    chartImages['report-score-trends-chart']
  );
  progress(62);

  // ── Page 5: Weekly Activity ───────────────────────────────
  addWeeklyActivityPage(
    doc,
    analyticsData.weeklyActivity,
    chartImages['report-weekly-activity-chart']
  );
  progress(68);

  // ── Page 6: Topic Analysis ────────────────────────────────
  addTopicAnalysisPage(doc, analyticsData.topicAnalysis);
  progress(74);

  // ── Page 7: MHT-CET Prediction ────────────────────────────
  addPredictionPage(doc, analyticsData.prediction);
  progress(80);

  // ── Page 8: Time Management ───────────────────────────────
  addTimeManagementPage(
    doc,
    analyticsData.timeDistribution,
    analyticsData.timeManagement,
    chartImages['report-time-distribution-chart']
  );
  progress(85);

  // ── Page 9: Error Patterns ────────────────────────────────
  addErrorPatternsPage(doc, analyticsData.errorPatterns);
  progress(90);

  // ── Page 10: Goals ────────────────────────────────────────
  addGoalsPage(doc, analyticsData.goals);
  progress(94);

  // ── Page 11: Final Summary ────────────────────────────────
  addFinalSummaryPage(doc, analyticsData);
  progress(97);

  // ── Add page numbers to all pages (except cover) ─────────
  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 2; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(doc, i - 1, totalPages - 1);
  }

  progress(99);

  // ── Download ──────────────────────────────────────────────
  const dateStr = new Date().toISOString().slice(0, 10);
  doc.save(`KakshaAI-Analytics-Report-${dateStr}.pdf`);

  progress(100);
}

export default generateAnalyticsReport;
